### ISSUE TITLE
Crash while downloading apk

### ISSUE THREAD

**Issue by Fi5t** [kiber-io/apkd#3]
Hello @kiber-io. When I tried to download apk with package name `com.vk.calls` I faced a strange error:
```
Traceback (most recent call last):
  File "/usr/local/bin/apkd", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/site-packages/apkd/main.py", line 168, in cli
    apkd.download_app(args.package, args.version_code if args.version_code is not None else -1, args.output)
  File "/usr/local/lib/python3.12/site-packages/apkd/main.py", line 99, in download_app
    apps, newest_version = self.get_app_info(package_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/apkd/main.py", line 79, in get_app_info
    app = source.get_app_info(package_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/apkd/sources/apkcombo.py", line 48, in get_app_info
    version = AppVersion(version_name, int(
                                       ^^^^
ValueError: invalid literal for int() with base 10: '1.114'
```

I use Docker to run your tool. The command looks like this:
```shell
docker run --rm -v ${PWD}:/usr/src/app apkd:1.0 -p com.vk.calls -d
```

Other apps download properly.

**Comment by kiber-io** [comment]
Hi! Thanks for the report, I will definitely check it out, but unfortunately in about a week I will only be able to

**Comment by kiber-io** [comment]
The old version is most likely installed. Try to upgrade and check with this package again. I can't repeat the error, everything works correctly with the specified package and source
